pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
//       when {
//         expression {
//           return params.BUILD_DOCKER == 'Y'
//         }
//       }
      steps {
        echo 'Build Docker Image'
        cat VERSION
//         sh "make build"
      }
    }
  }
//   post {
//       always {
//         sh "./deploy/build.sh reset_git_directory ${params.ENV}"
//         sh "./deploy/build.sh clean_unused_docker ${params.ENV}"
//       }
//     }
}
